export const actionTypes = {
          MAIN_HANDLE_HISTORY: '@@MAIN/MAIN_HANDLE_HISTORY',
          MAIN_HANDLE_INTERNATIONALIZATION: '@@MAIN/HANDLE_INTERNATIONALIZATION',
          MAIN_TO_TRANSLATE: '@@MAIN/TO_TRANSLATE',
          MAIN_SIDEBAR_CHANGE: "@@MAIN/SIDEBAR_CHANGE",
          SAGAS_HANDLE_LOCALE: 'SAGAS_HANDLE_LOCALE',
          SAGAS_MAIN_LOAD_USER: '@@MAIN_SAGAS/SAGAS_MAIN_LOAD_USER',

}

